name: validate and release
on:
  push:
    branches:
      - "**"

env:
  TERRAFORM_DOCS_VERSION: v0.16.0
  TFLINT_VERSION: v0.48.0

jobs:
  findModules:
    name: Collect workflow inputs
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.dirs.outputs.directories }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get root directories
        id: dirs
        uses: clowdhaus/terraform-composite-actions/directories@v1.8.3

  minVersionValidate:
    name: Min TF pre-commit
    needs: findModules
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.findModules.outputs.directories) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.2.4
        with:
          directory: ${{ matrix.directory }}

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory !=  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          args: "--color=always --show-diff-on-failure --files ${{ matrix.directory }}/*"

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.minVersion }}
        # Run only validate pre-commit check on min version supported
        if: ${{ matrix.directory ==  '.' }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.minVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          args: "--color=always --show-diff-on-failure --files $(ls *.tf)"

  maxVersionValidate:
    name: Max TF pre-commit
    runs-on: ubuntu-latest
    needs: findModules
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Terraform min/max versions
        id: minMax
        uses: clowdhaus/terraform-min-max@v1.2.4

      - name: Pre-commit Terraform ${{ steps.minMax.outputs.maxVersion }}
        uses: clowdhaus/terraform-composite-actions/pre-commit@v1.8.3
        with:
          terraform-version: ${{ steps.minMax.outputs.maxVersion }}
          tflint-version: ${{ env.TFLINT_VERSION }}
          terraform-docs-version: ${{ env.TERRAFORM_DOCS_VERSION }}
          install-hcledit: true

  release:
    # only run releases from master
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs:
      - minVersionValidate
      - maxVersionValidate
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: false # change to false when ready to release first major
        env:
          GITHUB_TOKEN: ${{ github.token }}
